project_name: kpop

before:
  hooks:
    - go mod tidy

release:
  github:
    owner: DDaaaaann
    name: kpop-cli

builds:
  - id: kpop
    main: ./cmd/kpop/main.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # add CGO settings if needed
    binary: kpop
    ldflags:
      - -s -w -X github.com/DDaaaaann/kpop-cli/cmd.version=v{{.Version}}
      - -s -w -X github.com/DDaaaaann/kpop-cli/cmd.commit={{.Commit}}
      - -s -w -X github.com/DDaaaaann/kpop-cli/cmd.date={{.Date}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
#      - LICENSE
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"