name: Pre-Release - Build, Test, E2E

on:
  push:
    branches:
      - master
      - 3-e2e-testing

jobs:
  build-matrix:
    name: Build Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install dependencies
        run: go mod tidy

      - name: Run unit tests
        run: go test -v ./...

      - name: Build binaries
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o dist/kpop-cli-${{ matrix.os }}-${{ matrix.arch }} ./cmd/kpop

      - name: Upload Binaries for E2E Testing
        uses: actions/upload-artifact@v3
        with:
          name: cli-binaries
          path: dist/

  e2e-test:
    needs: build-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ linux, windows, darwin ]
        arch: [ amd64, arm64 ]
    steps:
      - name: Download CLI Binaries
        uses: actions/download-artifact@v3
        with:
          name: cli-binaries
          path: dist/

      - name: Run E2E tests
        run: go test -v -tags=e2e ./internal

      - name: Delete Artifacts on Failure
        if: failure()
        uses: geekyeggo/delete-artifact@v2
        with:
          name: cli-binaries

  publish:
    name: Publish Artifact
    needs: e2e-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ linux, windows, darwin ]
        arch: [ amd64, arm64 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: kpop-cli-${{ matrix.os }}-${{ matrix.arch }}
          path: dist/kpop-cli-${{ matrix.os }}-${{ matrix.arch }}
